!function(e){var n={};function o(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,o),r.l=!0,r.exports}o.m=e,o.c=n,o.d=function(e,n,t){o.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},o.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},o.t=function(e,n){if(1&n&&(e=o(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(o.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var r in e)o.d(t,r,function(n){return e[n]}.bind(null,r));return t},o.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(n,"a",n),n},o.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},o.p="",o(o.s="./src/js/main.js")}({"./src/js/_vars.js":
/*!*************************!*\
  !*** ./src/js/_vars.js ***!
  \*************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony default export */ __webpack_exports__["default"] = ({\n  $window: window,\n  $document: document,\n  $html: document.documentElement,\n  $body: document.body\n});\n\n//# sourceURL=webpack:///./src/js/_vars.js?')},"./src/js/functions/stop-scroll.js":
/*!*****************************************!*\
  !*** ./src/js/functions/stop-scroll.js ***!
  \*****************************************/
/*! exports provided: disableScroll, enableScroll */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"disableScroll\", function() { return disableScroll; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"enableScroll\", function() { return enableScroll; });\nvar disableScroll = function disableScroll(fix) {\n  var paddingOffset = window.innerWidth - document.body.offsetWidth + 'px';\n  document.body.style.paddingRight = paddingOffset;\n  fix.forEach(function (el) {\n    el.style.paddingRight = paddingOffset;\n  });\n  var pagePosition = window.scrollY;\n  document.body.classList.add('disable-scroll');\n  document.body.dataset.position = pagePosition;\n  document.body.style.top = -pagePosition + 'px';\n};\nvar enableScroll = function enableScroll(fix) {\n  var pagePosition = parseInt(document.body.dataset.position, 10);\n  document.body.style.top = 'auto';\n  document.body.classList.remove('disable-scroll');\n  fix.forEach(function (el) {\n    el.style.paddingRight = '0px';\n  });\n  body.style.paddingRight = '0px';\n  window.scroll({\n    top: pagePosition,\n    left: 0\n  });\n  document.body.removeAttribute('data-position');\n};\n\n//# sourceURL=webpack:///./src/js/functions/stop-scroll.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _vars__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_vars */ \"./src/js/_vars.js\");\n/* harmony import */ var _functions_stop_scroll__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./functions/stop-scroll */ \"./src/js/functions/stop-scroll.js\");\n\n //disableScroll(fix) // fix -> class of element with position: fixed\n\nwindow.onload = function () {\n  var save = document.querySelector('.btn-save');\n  var notify = document.querySelector('.access__notify');\n  var close = document.querySelector('.notify__close');\n  var burger = document.querySelector('.header__burger');\n  var navClose = document.querySelector('.nav__close');\n  var nav = document.querySelector('.nav');\n  save.addEventListener('click', function (e) {\n    e.preventDefault();\n    notify.classList.add('access__notify--visible');\n  });\n  close.addEventListener('click', function () {\n    notify.classList.remove('access__notify--visible');\n  });\n  burger.addEventListener('click', function () {\n    nav.classList.add('nav--visible');\n  });\n  navClose.addEventListener('click', function () {\n    nav.classList.remove('nav--visible');\n  });\n};\n\n//# sourceURL=webpack:///./src/js/main.js?")}});